quarkus.package.type=legacy-jar

#App Config
quarkus.http.port=8080

#App Info
quarkus.application.name=citpdnd
quarkus.application.ui-header={applicationName} by DataManagementItalia | powered by Quarkus
quarkus.application.version=1.0.0
quarkus.banner.path=citpdnd.txt

# in caso di root context applicativo non "/" occorre impostare il root
# context per metrics e health
quarkus.http.non-application-root-path=/q

# per k8s occorre impostare l'endpoint di management su una porta differente da
# quella http del servizio e effettuare il binding su 0.0.0.0
quarkus.management.enabled=true
quarkus.management.host=0.0.0.0
# la porta standard per le metrics su k8s
quarkus.management.port=9000

# Gestione sicurezza
quarkus.http.cors=true
quarkus.http.cors.origins=*
quarkus.http.cors.access-control-allow-credentials=true
quarkus.http.cors.headers=Access-Control-Allow-Origin , content-type
quarkus.http.cors.methods=GET,PUT,POST
quarkus.tls.trust-all=true

#Logging
quarkus.log.file.enable=true
quarkus.log.file.path=/appserv/quarkus/sigit/logs/citpdnd.log
#quarkus.log.file.path=target/log/trace.log
quarkus.log.file.level=DEBUG
quarkus.log.file.rotation.max-backup-index=10
quarkus.log.file.rotation.file-suffix=.yyyy-MM-dd
quarkus.log.file.rotation.rotate-on-boot=true

# Disabilitazione OpenTelemetry exporter
quarkus.otel.enabled=false

# Datasource connection
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=<TO_DEFINE>
quarkus.datasource.password=<TO_DEFINE>
quarkus.datasource.jdbc.url=jdbc:postgresql://<TO_DEFINE>
quarkus.datasource.jdbc.max-size=16
quarkus.hibernate-orm.database.generation=none
quarkus.hibernate-orm.validate-in-dev-mode=false
quarkus.transaction-manager.default-transaction-timeout=1800

# token client
quarkus.rest-client.token.url=http://<TO_DEFINE>
token.client-id=<TO_DEFINE>
token.secret=<TO_DEFINE>

# index client
quarkus.rest-client.index.url=http://<TO_DEFINE>
index.key64=<TO_DEFINE>
index.tenant=sigit

# securizzazione embedded
quarkus.http.auth.basic=true

quarkus.security.users.embedded.enabled=true
quarkus.security.users.embedded.plain-text=true
quarkus.security.users.embedded.users.apiPdnd=<TO_DEFINE>
quarkus.security.users.embedded.roles.apiPdnd=reader