export const IMAGESURL = "assets/images/";
export const ICONSURL = "assets/icons/";


export interface EnvironmentConstants {
    IMAGESURL : string,
    ICONSURL: string,
    API_URL: string,
}

export const RUOLI = {
    RUOLO_RESPONSABILE: "RESPONSABILE",
    RUOLO_PROPRIETARIO: "PROPRIETARIO",
    RUOLO_RESPONSABILE_IMPRESA: "RESPONSABILE IMPRESA/ENTE",
    RUOLO_PROPRIETARIO_IMPRESA: "PROPRIETARIO IMPRESA/ENTE",
    RUOLO_ISPETTORE: "ISPETTORE",
    RUOLO_CARICATORE: "CARICATORE",
    RUOLO_IMPRESA: "IMPRESA",
    RUOLO_3RESPONSABILE: "3RESPONSABILE",
    RUOLO_DISTRIBUTORE: "DISTRIBUTORE",
    RUOLO_CAT: "SOGG. DELEGATO",
    CAT_RUOLO_PREFISSO: "SOGG. DELEGATO per ",
    RUOLO_SUPER: "SUPERUSER",
    RUOLO_VALIDATORE: "VALIDATORE",
    RUOLO_CONSULTATORE: "CONSULTATORE"
}