export const ICONSURL = "assets/icons/";

export const ESITO_OPERAZIONI = {
    PENDING: "IN ATTESA",
    SUCCESSO: "SUCCESSO",
    FALLITO: "FALLITO"
}

export const RUOLI = {
    RUOLO_RESPONSABILE: "RESPONSABILE",
    RUOLO_PROPRIETARIO: "PROPRIETARIO",
    RUOLO_RESPONSABILE_IMPRESA: "RESPONSABILE IMPRESA/ENTE",
    RUOLO_PROPRIETARIO_IMPRESA: "PROPRIETARIO IMPRESA/ENTE",
    RUOLO_ISPETTORE: "ISPETTORE",
    RUOLO_CARICATORE: "CARICATORE",
    RUOLO_IMPRESA: "IMPRESA",
    RUOLO_3RESPONSABILE: "3RESPONSABILE",
    RUOLO_DISTRIBUTORE: "DISTRIBUTORE",
    RUOLO_CAT: "SOGG. DELEGATO",
    CAT_RUOLO_PREFISSO: "SOGG. DELEGATO per ",
    RUOLO_SUPER: "SUPERUSER",
    RUOLO_VALIDATORE: "VALIDATORE",
    RUOLO_CONSULTATORE: "CONSULTATORE" 
}

export const STATO_RAPP = {
    BOZZA: 0,
    INVIATO: 1,
    RESPINTO: 2,
    IN_ATTESA_DI_INVIO: 3,
    IN_ATTESA_DI_MODIFICA: 4,
    IN_ATTESA_DI_ELIMINAZIONE: 5,
    BOZZA_LOCALE: -1
}

export const FORMAT = "MM/dd/yyyy";

export const MESSAGGIO_DECIMALE = "Ammette massimo {interi} interi e {decimali} decimali";



