import { RUOLI } from "./utils/constants";

export const PERMS = {
  [RUOLI.RUOLO_DISTRIBUTORE]: [
    'ELENCO_DATI_INVIATI',
    'CARICAMENTO_MANUALE_SEMPLIFICATO',
    'IMPORTAZIONE_XML',
    'CANCELLA_IMPORTAZIONE',
    'SALVA_CARICAMENTO_MANUALE',
    'ANNULLA_CARICAMENTO_MANUALE'
  ],
  [RUOLI.RUOLO_SUPER]: [
    'ELENCO_DATI_INVIATI',
    'CERCA_IMPRESE',
    'CARICAMENTO_MANUALE_SEMPLIFICATO',
    'IMPORTAZIONE_XML',
    'CANCELLA_IMPORTAZIONE',
    'SALVA_CARICAMENTO_MANUALE',
    'ANNULLA_CARICAMENTO_MANUALE'
  ],
  [RUOLI.RUOLO_CONSULTATORE]: [
    'ELENCO_DATI_INVIATI',
    'CERCA_IMPRESE'
  ]
};
